name: Hello World Workflow

on: 
    workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello, World!" 

    - name: show current date and time
      run: date

    - name: show current directory
      run: pwd