name: Terraform Basic Workflow

on: 
    pull_request:
      branches:
        - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Check Terraform formatting
      run: terraform fmt -check -recursive

    - name: intitialize Terraform
      run: terraform init

    - name: Validate terraform configuration
      run: terraform validate

    - name: Generate Terraform plan
      run: terraform plan -no-color