name: Terraform CI

on: 
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    terraform-ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Check Terraform formatting
              run: terraform fmt -check -recursive

            - name: intitialize Terraform
              run: terraform init

            - name: Validate terraform configuration
              run: terraform validate

            - name: Generate Terraform plan
              run: terraform plan -no-color

