name: Terraform CD

on: 
    push:
        branches:
            - main
            - test

permissions:
    contents: read

jobs:
    terraform-ci:
        runs-on: ubuntu-latest

        env: 
          TF_VAR_app_api_key: ${{ secrets.APP_API_KEY }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Confirm secret is available safely
              run: |
                if [ -z "$TF_VAR_app_api_key" ]; then
                  echo " secret APP_API_KEY is missing."
                  exit 1
                fi

                echo "APP_API_KEY secret is configured."

            - name: Check Terraform formatting
              run: terraform fmt -check -recursive

            - name: intitialize Terraform
              run: terraform init

            - name: Validate terraform configuration
              run: terraform validate

            - name: Generate Terraform plan
              run: terraform plan -out=tfplan

            - name: Convert plan to readable text
              run: terraform show -no-color tfplan > tfplan.txt


            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan

            - name: Show generated files safely
              run: | 
                echo "Generated files:"
                find generated -type f -maxdepth 2 -print

                echo ""
                echo "Generated Kubernetes deployment manifest: "
                cat generated/test-app-deployment.yaml

            - name: Upload Terraform apply artifact
              uses: actions/upload-artifact@v4
              with:
                name: Terraform-generated-demo
                path: |
                  generated/README>md
                  generated/test-app-deployment.yaml



